### ISSUE TITLE
No module named functools_util

### ISSUE THREAD

**Issue by ericcholis** [tellapart/commandr#10]
I'm getting the following error when I try to use commandr:

```
ImportError: No module named functools_util
```

It would appear that functools_util.py isn't being packaged with the module. As a test, I simply pasted it into my site-packages/commandr directory and the error goes away.

I'm a bit of a python newb, but I assume that `commandr/functools_util.py` needs to be added to commandr/MANIFEST

**Comment by kevinballard** [comment]
Updated the MANIFEST, and published a new release.
