### ISSUE TITLE
Converting options with underscore symbols to the hyphen/dash symbol

### ISSUE THREAD

**Issue by rubiojr** [tellapart/commandr#4]
This is a feature request folks, for the very nice commander!

It would be great to have option names like 'test_option' parsed as '--test-option' instead of '--test_option'. The reason is, perhaps, that there's a long tradition of options being parsed that way.

Since you may want to keep backwards compatibility, perhaps accepting both would be great and maybe display the built-in command help with the more common hyphen symbol instead of the underscore.

That is:

``` python
@command('run')
def run(test_option = 'foo'):
    pass
```

Would accept both --test-option and --test_option but the built-in help for the command would display --test-option.

Thanks!

**Comment by kevinballard** [comment]
Thanks for the suggestion. This is a good idea -- we'll probably integrate something like this into the next release.

**Comment by rubiojr** [comment]
Awesome @kevinballard, thanks!

**Comment by rudylattae** [comment]
+1

**Comment by kevinballard** [comment]
Integrated into release 1.1.0.

**Comment by rubiojr** [comment]
awesome! thanks.
